PIADAS_PERGUNTA_RESPOSTA = ["O que o pato disse para a pata?\nResposta: Vem Quá!",
"Porque o menino estava falando ao telefone deitado?\nResposta: Para não cair a ligação.",
"Qual é a fórmula da água benta?\nResposta: H Deus O!",
"Qual é a cidade brasileira que não tem táxi?\nResposta: Uberlândia.",
"O que o tijolo falou para o outro?\nResposta: Há um ciumento entre nós.",
"O que o tijolo falou para o outro?\nResposta: Há um ciumento entre nós.",
"Porque o Batman colocou o Bat-móvel no seguro?\nResposta: Porque ele tem medo que Robin!",
"Quem é a vó dos trigos?\nResposta: Avéia Quacker!",
"Qual é o alimento mais sagrado que existe?\nResposta: O amém doím.",
"Por que o rádio não pode ter filhos?\nResposta: Porque ele é estéreo.",
"Como se faz omelete de chocolate?\nResposta: Com ovos de páscoa.",
"O que um cromossomo falou para o outro?\nResposta: Cromossomos bonitos!",
"O que é um pontinho preto no avião?\nResposta: Uma aeromosca.",
"Qual é a galinha que cai no chão e surta?\nResposta: A galinha cai i pira.",
"Como o Batman faz para entrar na Bat-caverna?\nResposta: Ele bat-palma.",
"Qual é a diferença do lago e da padaria?\nResposta: No lago há sapinho e na padaria assa pão.",
"Qual é o melhor tratamento para pessoas que sofrem de queda constante?\nResposta: Para-quedismo.",
"Um tênis foi jogado ao mar e afundou. Qual o nome do filme?\nResposta: Titanike.",
"Por que a mulher do Hulk se divorciou dele?\nResposta: Porque ela queria um homem mais maduro",
"Qual é o tio da construção?\nResposta: O Tio Jolo",
"O que um álcool disse para outro álcool?\nResposta: Etanois!",
"Que raça de cachorro pula mais alto que um prédio?\nResposta: Qualquer uma, porque prédio não pula",
"Por que o pão não entende a batata?\nResposta: Porque o pão é francês e a batata é inglesa",
"Porque coalas não são ursos de verdade?\nResposta: Porque eles não têm coalaificação.",
"O que a zebra disse para a mosca?\nResposta: Você está na minha listra negra",
"Por que na Argentina as vacas vivem olhando para o céu?\nResposta: Porque tem boi nos ares!",
"Dois litros de leite atravessaram a rua e foram atropelados. Um morreu, o outro não. Por quê?\nResposta: Porque um deles era leite longa vida!",
"O que o tubarão disse quando comeu o peixe-palhaço?\nResposta: Que gosto engraçado!",
"O que o lápis disse para o papel?\nResposta: Você está me desapontando.",
"Quem é o rei dos queijos?\nResposta: O reiqueijão.",
"Por que a planta não responde?\nReposta: Porque ela é mudinha.",
"O que é um pontinho amarelo na piscina?\nResposta: O César Cyellow.",
"Qual foi o peixe que caiu do 15º andar?\nResposta: Aaaaaaaaaatum.",
"Qual é o carro que anuncia que vai chover?\nResposta: O Celta preto.",
"O que o ketchup disse para a batata?\nResposta: É nós na frita!",
"Por que a plantinha não pode passar mal de madrugada?\nResposta: Porque a essa hora só tem médico de plantão.",
"Qual é o país que distribui cana de açúcar?\nResposta: Cana dá.",
"Qual é o sapato que está sempre quebrado?\nResposta: O tá manco.",
"O que um macaco disse para o outro ao ver um elefante rosa subindo na árvore?\nResposta: Olha, um elefante rosa subindo na árvore.",
"O que aconteceu com o ferro de passar que caiu da mesa?\nResposta: Ficou passando mal.",
"Como o boi e a vaca pagaram a conta do jantar?\nResposta: Eles fizeram uma vaquinha.",
"Quais são as palavras que abrem muitas portas?\nResposta: Empurre e puxe.",
"O que fazer para ganhar um Chokito?\nResposta: Coloca o dedito na tomadita.",
"Por que o elefante não pega fogo?\nResposta: Porque ele é cinza.",
"Vó, por que você está há tanto tempo olhando o armário?\nResposta: Porque o médico mandou ficar de olho no açúcaResposta",
"Qual é o melhor chá para a calvície?\nResposta: Chá péu.",
"Por que os fantasmas são péssimos para contar mentiras?\nResposta: Porque são transparentes.",
"O que a Lua disse ao Sol?\nResposta: Nossa, você é tão grande e ainda não te deixam sair à noite!",
"Você sabe por que a água foi presa?\nResposta: Porque ela matou a sede.",
"Miguel, aonde vai tão circunspecto e assaz atribulado?\nResposta: Eu ia no banheiro, mas agora vou consultar um dicionário.",
"Qual o contrário de papelada?\nResposta: Pá vestida.",
"O que o cadarço falou para o tênis?\nResposta: Eu me amarro em você.",
"Por que o porco está sempre feliz?\nResposta: Porque vive de bacon a vida.",
"Qual a diferença entre o gato e coca-cola?\nResposta: O gato mia e a coca light.",
"Qual é o cúmulo da solidão?\nResposta: Morar sozinho e fugir de casa.",
"Por que o cachorro entrou na igreja?\nResposta: Porque é um pastor alemão.",
"Por que Napoleão era sempre chamado para as festas na França?\nResposta: porque ele era Bom Na Party.",
"Na frase “ele acordou cedo”, onde está o sujeito?\nResposta: Em algum lugar com sono.",
"O que o pagodeiro foi fazer na igreja?\nResposta: Foi cantar Pá God.",
"Na frase “Proibido estacionar”, qual é o sujeito da oração?\nResposta: Sujeito a guincho.",
"O que a galinha foi fazer na igreja?\nResposta: Assistir a Missa do Galo.",
"Por que a velhinha não usa relógio?\nResposta: Porque ela é sem hora.",
"Havia dois caminhões voando. Um caiu. No entanto, por que o outro continuou voando?\nResposta: Porque era caminhão-pipa.",
"Qual a fruta que anda na montanha Russa?\nResposta: O kiwiiiii.",
"Por que o mouse é muito mimado?\nResposta: Porque tudo o que ele quer, o mouse pad.",
"Por que o pinheiro não se perde na floresta?\nResposta: Porque ele tem uma pinha (um mapinha).",
"Como transformar o giz em uma cobra?\nResposta: É só colocar ele na água que o GIZBÓIA!",
"O que fala o livro de Matemática para o livro de História?\nResposta: Não me venha com história que eu já estou cheio de problema!",
"Qual é o mercado que voa?\nResposta: É o super-mercado!",
"Qual é o fim da picada?\nResposta: Quando o mosquito vai embora.",
"Qual animal não vale mais nada?\nResposta: O Javali",
"Qual a tecla preferida do astronauta?\nResposta: O espaço.",
"O que o alienígena foi fazer em São Paulo?\nResposta: Foi visitar o Tioetê.",
"Por que o bombeiro não gosta de andar?\nResposta: Pq ele socorre.",
"O que tem debaixo do tapete de um hospício?\nResposta: Um doido varrido.",
"O que um prédio falou para o outro?\nResposta: Nossa você tem um andar maravilhoso.",
"Um decorador foi ao cardiologista, ele está com problema de que?\nResposta: Decoração",
"Qual o queijo que mais sofre?\nResposta: O Queijo Ralado",
"Qual remédio avisa quando você está bebendo demais?\nResposta: O paracetamal.",
"Onde os ursos polares guardam o seu dinheiro?\nResposta: Em um banco de neve",
"O que o zero disse para o oito?\nResposta: Belo cinto!",
"O que pediu o astronauta claustrofóbico?\nResposta: Um pouco de espaço",
"Quem é o rei da horta?\nResposta: O rei-polho",
"Qual é a comida que liga e desliga?\nResposta: O Strog-ON-OFF",
"Por que as estrelas não fazem miau?\nResposta: Porque Astro-não-mia",
"Qual é a doença que o pneu mais pega?\nResposta: Pneumonia.",
"Por que o pedreiro terminou o namoro?\nResposta: Porque não era concreto.",
"O que o tomate foi fazer no banco?\nResposta: Tirar o extrato.",
"Como se chama o rio mais azedo do Brasil?\nResposta: O Rio só limões.",
"Porque o elefante usa óculos vermelho?\nResposta: Para Vermelhor",
"Por que o computador foi preso?\nResposta: Porque ele executou um programa.",
"Sabe por que eu não conto piadas sobre obras?\nResposta: Porque elas ainda estão em construção",
"Por que a loira toma banho com o chuveiro desligado?\nResposta: Porque comprou xampu para cabelos secos.",
"Por que o menino colocou o despertador embaixo da cama?\nResposta: Para acordar em cima da hora.",
"Por que tem uma cama elástica no Polo Norte?\nResposta: Para o urso polar.",
"O que os matemáticos disseram à pessoa que criou o zero?\nResposta: Obrigado por nada.",
"O que é que o cavalo foi fazer no orelhão?\nResposta: Passar um trote.",
"Por que mulher não pode ser eletricista?\nResposta: Porque leva 9 meses para dar à luz.",
"Quem é que fala errado: o Cebolinha ou a Mônica?:Resposta: A Mônica, o cebolinha fala elado.",
"O que é bom para terçol?\nResposta: Não ter chuva.",
"Qual é a diferença entre a bicicleta e a privada?\nResposta: A bicicleta, você senta pra correr. Já a privada, você corre para sentar.",
"O que é um pontinho verde no aeroporto internacional?\nResposta: Um greengo.",
"O que é o sapo está fazendo no computador?\nResposta: Procurando a RAM",
"O que é um pontinho vermelho no rio?\nResposta: Um Jacared.",
"O que são 4 pontinhos no jardim?\nResposta: Fourmigas",
"Por que o Super Mário entrou na terapia?\nResposta: Porque está passando por uma fase difícil.",
"O que é um pontinho amarelo tocando violão?\nResposta: Cheetos Buarque.",
"Por que os robôs não têm medo?\nResposta: Porque eles têm os nervos de aço.",
"O que são dois pontinhos cinza no fundo do mar?\nResposta: Two-barão.",
"O que é um pontinho marrom cantando rap no palco?\nResposta: É o Mano Brown."]
